pizza/config/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from features.views import index
from order.views import create_order, create_model_order

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('order/create/', create_order, name='createorder'),
    path('createmodelorder/', create_model_order, name='createmodelorder'),
    path('__debug__/', include(debug_toolbar.urls)),    
]

pizza/features/models.py
from django.db import models

# Create your models here.

pizza/order/models.py
from django.db import models
from pizza.models import PizzaModel
from django.utils.translation import gettext_lazy as _

# Create your models here
class OrderModel(models.Model):
    class DeliveryStatus(models.TextChoices):
        PENDING = 'PEN', _('Pending')
        DELIVERED = 'DEL', _('Delivered')
    address = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    pizza_order = models.ManyToManyField(PizzaModel)
    delivery_status = models.CharField(
        max_length=3,
        choices=DeliveryStatus.choices,
        default=DeliveryStatus.PENDING
    )
    class Meta:
        verbose_name='Orders'
        verbose_name_plural = 'Orders'
        
    def __str__(self):
        return f'Address: {self.address}, Order: {", ".join([pizza.name for pizza in self.pizza_order.all()])}'
    
    def all_orders(self):
        return "\n".join([o.name for o in self.pizza_order.all()])
    
class OrderProxy(OrderModel.pizza_order.through):
    class Meta:
        proxy = True
    
    def __str__(self):
        return str(self.ordermodel)
        

pizza/pizza/models.py
from django.db import models

# Create your models here.
class ToppingsModel(models.Model):
    name = models.CharField(max_length=50)
    
    class Meta:
        verbose_name = 'Toppings(vn)'
        verbose_name_plural = 'Toppings(vnp)'
    
    def __str__(self):
        return self.name
class PizzaModel(models.Model):   
    name = models.CharField(max_length=50)
    toppings = models.ManyToManyField(ToppingsModel, verbose_name='toppings')
    
    class Meta:
        verbose_name = 'My pizza resipes(vn)'
        verbose_name_plural = 'Pizza resipes(vnp)'
        
    def __str__(self):
        return f'{self.name} : {",".join([topping.name for topping in self.toppings.all()])}'
    
    def all_toppings(self):
        return "\n".join([t.name for t in self.toppings.all()])
    
class PizzaProxy(PizzaModel.toppings.through):
    class Meta:
        proxy = True
        
    def __str__(self):
        return str(self.toppingsmodel)

pizza/order/forms.py
from django import forms
from pizza.models import PizzaModel
from .models import OrderModel

PIZZAS =[
    (f'{p.id}', f'{p.name}') for p in PizzaModel.objects.all()
]

class CreateForm(forms.Form):
    address = forms.CharField()
    choice = forms.ChoiceField(
        choices=PIZZAS,
        help_text='If you want some extra. Send us <a href="#>message</a>',
        widget=forms.Select(attrs={'class': 'pizzas'}))
    
class CreateOrderModelForm(forms.ModelForm):
    error_css_class = 'error-field-class'
    required_css_class = 'required-field-class'
    class Meta:
        model = OrderModel
        fields = ['address', 'pizza_order']
        widgets = {
            'address': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your address: '
            }),
            'pizza_order': forms.CheckboxSelectMultiple()
        }

pizza/features/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    data = [i for i in range(10)]
    return render(request, 'index.html', {'test_data': data})

pizza/order/views.py
from django.shortcuts import render, redirect
from pizza.models import PizzaModel
from .models import OrderModel
from .forms import CreateForm, CreateOrderModelForm
from django.forms import modelformset_factory

# Create your views here.
def create_order(request, *args, **kwargs):
    all_pizzas = PizzaModel.objects.all()
    order_form = CreateForm(request.POST or None)

    if order_form.is_valid():
        address = order_form.cleaned_data.get('address')
        order = dict(order_form.data).get('choice')
        pizza = [PizzaModel.objects.get(pk = i) for i in order]
        new_order = OrderModel(address=address)
        new_order.save()
        new_order.pizza_order.add(*pizza)
        new_order.save()
        return redirect('createorder')
        
        # new_order = OrderModel.objects.create(address = address)
        # pizza = PizzaModel.objects.get(pk = order)
        # new_order.pizza_order.add(pizza)
        # new_order.save()
    
    context = {
        'pizzas': all_pizzas,
        'order_form': order_form
    }
    return render(request, 'order/create_order.html', context = context)

def create_model_order(request, *args, **kwargs):
    pizzas = PizzaModel.objects.all()
    model_form = CreateOrderModelForm(request.POST or None)
    # OrderFormSet = modelformset_factory(
    #     OrderModel,
    #     form=CreateOrderModelForm,
    #     extra=2)
    # model_form = OrderFormSet(
    #     request.POST or None,
    #     queryset=OrderModel.objects.none(),
    #     initial=[{
    #         'address': 'modelformset street'
    #     }])
    # if model_form.is_valid():
    #     model_form.save()
    #     return redirect('createmodelorder')
    context = {
        'pizzas': pizzas,
        'model_form': model_form,
    }
    return render(request, 'order/create_model_order.html', context=context)

pizza/pizza/views.py
from django.shortcuts import render

# Create your views here.

pizza/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for data in test_data %}
        <ul>
            <li>{{data}}</li>
        </ul>
    {% endfor %}
</body>
</html>

pizza/templates/order/create_model_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Our pizzas! Tasty and delitious!</h1>
    <ul>
        {% for pizza in pizzas %}
            <li>{{pizza.name}}</li>
            <div class="">
                <mark>Ingridients</mark>
            </div>
            {% for i in pizza.toppings.all %}
                <ul>{{i.name}}</ul>
            {% endfor %}
        {% endfor %}
    </ul>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ model_form.as_p }}
        <input type="submit" value="place order">
    </form>
    <button class="more">add more pizza</button>
</body>
<script>
    let pizza = document.querySelector('#id_pizza_order')
    let order = document.querySelector('.order')
    let more = document.querySelector('.more')
    let form = document.querySelector('.form')

    more.addEventListener('click', (e) => {
        e.preventDefault()
        p = document.createElement('p')
        l = document.createElement('label')
        l.setAttribute('for', 'id_pizza_order')
        l.textContent = 'Pizza order: '
        cloned = pizza.cloneNode(true)
        p.append(l)
        p.append(cloned)
        form.insertBefore(p, order)
    })
</script>
</html>

pizza/templates/order/create_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Our pizzas! Tasty and delitious!</h1>
    <ul>
        {% for pizza in pizzas %}
            <li>{{pizza.name}}</li>
            <div class="">
                <mark>Ingridients</mark>
            </div>
            {% for i in pizza.toppings.all %}
                <ul>{{i.name}}</ul>
            {% endfor %}
        {% endfor %}
    </ul>
    <h1>Order your pizza now!</h1>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {% for field in order_form %}
            <div>
                {{ field.label_tag }} {{ field }}
            </div>
            {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>  
            {% endif %}
            {% if field.errors %}
                {% for error in field.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %}
        {% endfor %}
        <input type="submit" class="order" value="place order">
        
        <!-- <h3>Address: {{order_form.address}}</h3>
        <h3>Choice: {{order_form.choice}}</h3>
        {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
        <button type="submit" class="order" value="place_order">place_order</button> -->
    </form>
    <button class='more'>add more pizza</button>
</body>
<script>
    let pizza = document.querySelector('.pizzas')
    let order = document.querySelector('.order')
    let more = document.querySelector('.more')
    let form = document.querySelector('.form')

    more.addEventListener('click', (e) => {
        e.preventDefault()
        p = document.createElement('p')
        l = document.createElement('label')
        l.setAttribute('for', 'id_choice')
        l.textContent = 'Choice: '
        cloned = pizza.cloneNode(true)
        p.append(l)
        p.append(cloned)
        form.insertBefore(p, order)
    })
</script>
</html>